name: Deploy to EC2

on:
  push:
    branches:
      - Admin_Panel
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/admin-panel:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Astroway/Admin-Backend
          
          # Log in to Docker Hub
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Stop and remove old container
          docker stop admin-panel-container || true
          docker rm admin-panel-container || true
          
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/admin-panel:latest
          
          # Clean up old images (not the latest)
          docker image prune -af --filter "until=24h"
          
          # Run the new container
          docker run -d -p 8082:8080 --name admin-panel-container --env-file .env --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/admin-panel:latest